server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clarity
    username: clarityuser
    password: claritypass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  sql:
    init:
      platform: postgres